# HMS Networks; Americas
# Application Bug Report Template for Maven-based Ewon ETK Projects
# Version: 3.0.0
# Date: February 8, 2024
#
# This template provides an option when creating a new issue to report an
# application bug using a structured format.

name: Bug Report
description: Create a new bug report to help us improve the project.
title: "[BUG] <title>"
labels: [ 'bug' ]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear and concise description of the bug you are experiencing.
  - type: checkboxes
    attributes:
      label: 'Do I have the latest version of the Ewon firmware?'
      description: 'Application updates and patches are tested using latest version of the Ewon firmware at the time of release.'
      options:
        - label: 'Yes'
          required: true
  - type: checkboxes
    attributes:
      label: 'Do I have the latest version of the application?'
      description: 'Some bugs may have been fixed in the latest version of the application.'
      options:
        - label: 'Yes'
          required: true
  - type: checkboxes
    attributes:
      label: 'Do I have a custom or modified version of the application?'
      description: 'Some bugs may be specific to custom or modified versions of the application.'
      options:
        - label: 'Yes'
          required: true
  - type: input
    id: firmware-version
    attributes:
      label: 'Ewon Firmware Version'
      description: 'The version of the Ewon firmware you are using.'
      placeholder: 'e.g. 14.8s0'
    validations:
      required: true
  - type: input
    id: application-version
    attributes:
      label: 'Application Version'
      description: 'The version of the application you are using.'
      placeholder: 'e.g. 1.0.0'
    validations:
      required: true
  - type: dropdown
    id: network-connection-type
    attributes:
      label: 'Network Connection Type'
      description: 'The type of network connection you are using.'
      options:
        - 'Ethernet'
        - 'Wi-Fi'
        - 'Cellular'
        - 'Other/Unsure'
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: 'Current Behavior'
      description: 'A clear and concise description of what is currently happening. Please include any error messages or logs.'
      placeholder: 'I was trying to do X, but Y happened instead.'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'Expected Behavior'
      description: 'A clear and concise description of what you expected to happen.'
      placeholder: 'I expected X to happen.'
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 'Steps to Reproduce'
      description: 'Please provide detailed steps to reproduce the bug.'
      placeholder: '1. Go to "..."'
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If this issue is not easily reproducible, please take a backup of your Ewon including support files.
        To better diagnose the issue, it is important that the backup be taken while the issue is occurring, or as soon as possible after the issue occurs.
        If requested, be prepared to provide this backup to HMS Networks support.
  - type: textarea
    id: additional-information
    attributes:
      label: 'Additional Information'
      description: 'Please provide any additional information that may be helpful in diagnosing the bug.'
      placeholder: 'I have tried X, Y, and Z to fix the issue, but nothing has worked.'
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: 'Code of Conduct'
      description: 'By submitting this issue, you agree to abide by our [Code of Conduct](CODE_OF_CONDUCT.md).'
      options:
        - label: 'I agree to abide by the Code of Conduct.'
          required: true
  - type: markdown
    attributes:
      value: |
        <h5>Privacy Notice</h5>
        This form creates a GitHub issue in the repository for this project, which may be publicly accessible or shared with third parties.
        Please do not include any sensitive information, including device backup files.
        Sensitive information should be provided to HMS Networks Support when requested.