# HMS Networks; Americas
# Documentation Issue Report Template for Maven-based Ewon ETK Projects
# Version: 3.0.0
# Date: February 8, 2024
#
# This template provides an option when creating a new issue to report an
# error or mistake in the documentation using a structured format.

name: Documentation Issue Report
description: Create a new documentation issue report to help us improve the project.
title: "[DOC] <title>"
labels: [ 'documentation' ]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear and concise description of the documentation issue or mistake you have found.
  - type: input
    id: page-url
    attributes:
      label: 'Page URL'
      description: 'The URL of the documentation page where the issue or mistake is located.'
      placeholder: 'e.g. https://hms-networks.github.io/sc-java-maven-starter-project/docs'
    validations:
      required: true
  - type: input
    id: issue-description
    attributes:
      label: 'Issue Description'
      description: 'A clear and concise description of the issue or mistake you have found.'
      placeholder: 'e.g. The code example on this page is incorrect.'
    validations:
      required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: 'Code of Conduct'
      description: 'By submitting this issue, you agree to abide by our [Code of Conduct](CODE_OF_CONDUCT.md).'
      options:
        - label: 'I agree to abide by the Code of Conduct.'
          required: true
  - type: markdown
    attributes:
      value: |
        <h5>Privacy Notice</h5>
        This form creates a GitHub issue in the repository for this project, which may be publicly accessible or shared with third parties.
        Please do not include any sensitive information, including device backup files.
        Sensitive information should be provided to HMS Networks Support when requested.