# HMS Networks; Americas
# Other/Unknown Report Template for Maven-based Ewon ETK Projects
# Version: 3.0.0
# Date: February 8, 2024
#
# This template provides an option when creating a new issue to report an
# unknown or other issue using a structured format.

name: Other Report
description: Create a new report to help us improve the project.
title: "[OTHER] <title>"
labels: [ 'help wanted', 'needs investigation' ]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear and concise description of the report you are submitting.
  - type: checkboxes
    attributes:
      label: 'Do I have a custom or modified version of the application?'
      description: 'Some questions or concerns may be specific to custom or modified versions of the application.'
      options:
        - label: 'Yes'
          required: true
  - type: input
    id: firmware-version
    attributes:
      label: 'Ewon Firmware Version'
      description: 'The version of the Ewon firmware you are using.'
      placeholder: 'e.g. 14.8s0'
    validations:
      required: true
  - type: input
    id: application-version
    attributes:
      label: 'Application Version'
      description: 'The version of the application you are using.'
      placeholder: 'e.g. 1.0.0'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'A clear and concise description of the report you are submitting.'
      placeholder: 'e.g. What is occurring? Is there an issue or concern?'
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: 'Additional Information'
      description: 'Please provide any additional information that may be helpful.'
      placeholder: 'e.g. The issue or concern is causing X, Y, and Z.'
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: 'Code of Conduct'
      description: 'By submitting this report, you agree to abide by our [Code of Conduct](CODE_OF_CONDUCT.md).'
      options:
        - label: 'I agree to abide by the Code of Conduct.'
          required: true
  - type: markdown
    attributes:
      value: |
        <h5>Privacy Notice</h5>
        This form creates a GitHub issue in the repository for this project, which may be publicly accessible or shared with third parties.
        Please do not include any sensitive information, including device backup files.
        Sensitive information should be provided to HMS Networks Support when requested.