# HMS Networks Solution Center
# Build Test Action for Maven-based Ewon ETK Projects
# Version: 2.1
#
# This action is configured to automatically run when a push
# is made or pull request is merged to the `main` branch.

name: Build Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 16

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            target/buildJdk
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Package Java Files With Maven
        run: mvn package -f pom.xml