# HMS Networks; Americas
# JUnit Test Action for Maven-based Ewon ETK Projects
# Version: 3.0.0
# Date: February 8, 2024
#
# This action is configured to automatically run when a push
# is made to the `main` branch or a pull request for the `main`
# branch.

name: JUnit Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  junit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 16
          cache: 'maven'

      - name: Run JUnit Testing With Maven
        run: mvn test -f pom.xml

      - name: Upload Test Report(s)
        uses: actions/upload-artifact@v3
        with:
          name: JUNIT-TEST-REPORTING-${{ github.sha }}-${{ github.event.repository.name }}
          path: |
            target/surefire-reports
            target/site